# Tuple vs List

In [6]:
_tuple = (1,'a',2,'b')
_list = [1,'a',2,'b']

# List operations
## Concat

In [5]:
print( [1,2] + [3,4] )

[1, 2, 3, 4]


## Repeat

In [4]:
print( [1,3]*3 )

[1, 3, 1, 3, 1, 3]


# Slising lists

In [36]:
import numpy as np
import pandas as pd
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
print( x[-5:-2] )

[5 6 7]


In [14]:
print( x[:5])
print( x[5:])

[0 1 2 3 4]
[5 6 7 8 9]


In [15]:
print(x[1::2])
print(x[1:5:2])

[1 3 5 7 9]


# Time

In [20]:
import time as tm
import datetime as dt

stamp = tm.time()
stamp

1502649837.447468

In [21]:
dtnow = dt.datetime.fromtimestamp(stamp)
dtnow

datetime.datetime(2017, 8, 13, 20, 43, 57, 447468)

In [22]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2017, 8, 13, 20, 43, 57)

In [26]:
delta = dt.timedelta(days=100)
then = dt.date.today()- delta
then

datetime.date(2017, 5, 5)

# Lambda

In [27]:
myfunc = lambda a,b,c: a+b
print( myfunc(1,2,3))

3


In [28]:
my_list = [number for number in range(0,10) if number % 2 == 0]

# Numpy

In [30]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
v = np.arange(1,10,2)
print(o)
print(v)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4. ]
[1 3 5 7 9]


In [33]:
v[v%3 ==0]

array([3, 9])

# Performance

In [38]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
s+=2

10 loops, best of 3: 280 µs per loop
